// Code generated by protoc-gen-go-lrpc. DO NOT EDIT.
package raft

/*
   @Generator   : protoc-gen-go-lrpc
   @CreateTime  : 2026-09-15 23:04:47.708522 +0800 CST
   @Author      : NoAuthor
   @Comment     : code is auto generate do not edit
*/

import (
	"github.com/nyan233/littlerpc/core/common/context"
	"github.com/nyan233/littlerpc/core/common/metadata"
	"github.com/nyan233/littlerpc/core/server"
)

type RaftServer interface {
	RequestVote(ctx *context.Context, req *RequestVoteReq) (rsp *RequestVoteRsp, err error)
	AppendEntries(ctx *context.Context, req *AppendEntriesReq) (rsp *AppendEntriesRsp, err error)
	InstallSnapshot(ctx *context.Context, req *InstallSnapshotReq) (rsp *InstallSnapshotRsp, err error)
	GetLeader(ctx *context.Context, req *GetLeaderReq) (rsp *GetLeaderRsp, err error)
	AppendCommands(ctx *context.Context, req *AppendCommandsReq) (rsp *AppendCommandsRsp, err error)
}

type UnImplRaftServer struct{}

func (s UnImplRaftServer) RequestVote(ctx *context.Context, req *RequestVoteReq) (rsp *RequestVoteRsp, err error) {
	panic("not implemented")
}

func (s UnImplRaftServer) AppendEntries(ctx *context.Context, req *AppendEntriesReq) (rsp *AppendEntriesRsp, err error) {
	panic("not implemented")
}

func (s UnImplRaftServer) InstallSnapshot(ctx *context.Context, req *InstallSnapshotReq) (rsp *InstallSnapshotRsp, err error) {
	panic("not implemented")
}

func (s UnImplRaftServer) GetLeader(ctx *context.Context, req *GetLeaderReq) (rsp *GetLeaderRsp, err error) {
	panic("not implemented")
}

func (s UnImplRaftServer) AppendCommands(ctx *context.Context, req *AppendCommandsReq) (rsp *AppendCommandsRsp, err error) {
	panic("not implemented")
}

var RaftServerDesc = server.Desc{
	Package: "raft",
	ServiceMethods: map[string][]server.ServiceMethod{
		"raft": {
			{
				Name:    "RequestVote",
				Options: nil,
			},
			{
				Name:    "AppendEntries",
				Options: nil,
			},
			{
				Name:    "InstallSnapshot",
				Options: nil,
			},
			{
				Name:    "GetLeader",
				Options: nil,
			},
			{
				Name:    "AppendCommands",
				Options: nil,
			},
		},
	},
}

func RegisterRaftServer(s *server.Server, i interface{}, option map[string]metadata.ProcessOption) error {
	_ = i.(RaftServer)
	return s.RegisterClass("raft", i, option)
}
