// Code generated by protoc-gen-go-lrpc. DO NOT EDIT.
package raft

/*
   @Generator   : protoc-gen-go-lrpc
   @CreateTime  : 2026-09-22 15:17:42.024159 +0800 CST
   @Author      : NoAuthor
   @Comment     : code is auto generate do not edit
*/

import (
	"github.com/nyan233/littlerpc/core/client"
	"github.com/nyan233/littlerpc/core/common/context"
)

var (
	_ caller0968f8accb734a5b94c1f7227e6bdcf8 = new(client.Client)
	_ RaftProxy                              = new(raftImpl)
)

type caller0968f8accb734a5b94c1f7227e6bdcf8 interface {
	Request2(service string, opts []client.CallOption, reqCount int, args ...interface{}) error
}

type RaftProxy interface {
	RequestVote(a0 *context.Context, a1 *RequestVoteReq, opts ...client.CallOption) (r0 *RequestVoteRsp, r1 error)
	AppendEntries(a0 *context.Context, a1 *AppendEntriesReq, opts ...client.CallOption) (r0 *AppendEntriesRsp, r1 error)
	InstallSnapshot(a0 *context.Context, a1 *InstallSnapshotReq, opts ...client.CallOption) (r0 *InstallSnapshotRsp, r1 error)
	GetLeader(a0 *context.Context, a1 *GetLeaderReq, opts ...client.CallOption) (r0 *GetLeaderRsp, r1 error)
	AppendCommands(a0 *context.Context, a1 *AppendCommandsReq, opts ...client.CallOption) (r0 *AppendCommandsRsp, r1 error)
}

type raftImpl struct {
	caller0968f8accb734a5b94c1f7227e6bdcf8
}

func NewRaft(b caller0968f8accb734a5b94c1f7227e6bdcf8) RaftProxy {
	proxy := new(raftImpl)
	c, ok := b.(caller0968f8accb734a5b94c1f7227e6bdcf8)
	if !ok {
		panic("the argument is not implemented caller")
	}
	proxy.caller0968f8accb734a5b94c1f7227e6bdcf8 = c
	return proxy
}

func (p raftImpl) RequestVote(a0 *context.Context, a1 *RequestVoteReq, opts ...client.CallOption) (r0 *RequestVoteRsp, r1 error) {
	r0 = new(RequestVoteRsp)
	r1 = p.Request2("raft.RequestVote", opts, 2, a0, a1, r0)
	return
}

func (p raftImpl) AppendEntries(a0 *context.Context, a1 *AppendEntriesReq, opts ...client.CallOption) (r0 *AppendEntriesRsp, r1 error) {
	r0 = new(AppendEntriesRsp)
	r1 = p.Request2("raft.AppendEntries", opts, 2, a0, a1, r0)
	return
}

func (p raftImpl) InstallSnapshot(a0 *context.Context, a1 *InstallSnapshotReq, opts ...client.CallOption) (r0 *InstallSnapshotRsp, r1 error) {
	r0 = new(InstallSnapshotRsp)
	r1 = p.Request2("raft.InstallSnapshot", opts, 2, a0, a1, r0)
	return
}

func (p raftImpl) GetLeader(a0 *context.Context, a1 *GetLeaderReq, opts ...client.CallOption) (r0 *GetLeaderRsp, r1 error) {
	r0 = new(GetLeaderRsp)
	r1 = p.Request2("raft.GetLeader", opts, 2, a0, a1, r0)
	return
}

func (p raftImpl) AppendCommands(a0 *context.Context, a1 *AppendCommandsReq, opts ...client.CallOption) (r0 *AppendCommandsRsp, r1 error) {
	r0 = new(AppendCommandsRsp)
	r1 = p.Request2("raft.AppendCommands", opts, 2, a0, a1, r0)
	return
}
