// Code generated by protoc-gen-go-lrpc. DO NOT EDIT.
package raft

/*
   @Generator   : protoc-gen-go-lrpc
   @CreateTime  : 2026-09-24 19:17:24.635112 +0800 CST
   @Author      : NoAuthor
   @Comment     : code is auto generate do not edit
*/

import (
	"github.com/nyan233/littlerpc/core/client"
	"github.com/nyan233/littlerpc/core/common/context"
)

var (
	_ caller33bf980e27224367980c64673f6c1991 = new(client.Client)
	_ RaftProxy                              = new(raftImpl)
)

type caller33bf980e27224367980c64673f6c1991 interface {
	Request2(service string, opts []client.CallOption, reqCount int, args ...interface{}) error
}

type RaftProxy interface {
	RequestVote(a0 *context.Context, a1 *RequestVoteReq, opts ...client.CallOption) (r0 *RequestVoteRsp, r1 error)
	AppendEntries(a0 *context.Context, a1 *AppendEntriesReq, opts ...client.CallOption) (r0 *AppendEntriesRsp, r1 error)
	InstallSnapshot(a0 *context.Context, a1 *InstallSnapshotReq, opts ...client.CallOption) (r0 *InstallSnapshotRsp, r1 error)
	GetLeader(a0 *context.Context, a1 *GetLeaderReq, opts ...client.CallOption) (r0 *GetLeaderRsp, r1 error)
	AppendCommands(a0 *context.Context, a1 *AppendCommandsReq, opts ...client.CallOption) (r0 *AppendCommandsRsp, r1 error)
	LocalRead(a0 *context.Context, a1 *LocalReadReq, opts ...client.CallOption) (r0 *LocalReadRsp, r1 error)
	LinnerRead(a0 *context.Context, a1 *LinnerReadReq, opts ...client.CallOption) (r0 *LinnerReadRsp, r1 error)
	AddServer(a0 *context.Context, a1 *AddServerReq, opts ...client.CallOption) (r0 *AddServerRsp, r1 error)
	RemoveServer(a0 *context.Context, a1 *RemoveServerReq, opts ...client.CallOption) (r0 *RemoveServerRsp, r1 error)
}

type raftImpl struct {
	caller33bf980e27224367980c64673f6c1991
}

func NewRaft(b caller33bf980e27224367980c64673f6c1991) RaftProxy {
	proxy := new(raftImpl)
	c, ok := b.(caller33bf980e27224367980c64673f6c1991)
	if !ok {
		panic("the argument is not implemented caller")
	}
	proxy.caller33bf980e27224367980c64673f6c1991 = c
	return proxy
}

func (p raftImpl) RequestVote(a0 *context.Context, a1 *RequestVoteReq, opts ...client.CallOption) (r0 *RequestVoteRsp, r1 error) {
	r0 = new(RequestVoteRsp)
	r1 = p.Request2("raft.RequestVote", opts, 2, a0, a1, r0)
	return
}

func (p raftImpl) AppendEntries(a0 *context.Context, a1 *AppendEntriesReq, opts ...client.CallOption) (r0 *AppendEntriesRsp, r1 error) {
	r0 = new(AppendEntriesRsp)
	r1 = p.Request2("raft.AppendEntries", opts, 2, a0, a1, r0)
	return
}

func (p raftImpl) InstallSnapshot(a0 *context.Context, a1 *InstallSnapshotReq, opts ...client.CallOption) (r0 *InstallSnapshotRsp, r1 error) {
	r0 = new(InstallSnapshotRsp)
	r1 = p.Request2("raft.InstallSnapshot", opts, 2, a0, a1, r0)
	return
}

func (p raftImpl) GetLeader(a0 *context.Context, a1 *GetLeaderReq, opts ...client.CallOption) (r0 *GetLeaderRsp, r1 error) {
	r0 = new(GetLeaderRsp)
	r1 = p.Request2("raft.GetLeader", opts, 2, a0, a1, r0)
	return
}

func (p raftImpl) AppendCommands(a0 *context.Context, a1 *AppendCommandsReq, opts ...client.CallOption) (r0 *AppendCommandsRsp, r1 error) {
	r0 = new(AppendCommandsRsp)
	r1 = p.Request2("raft.AppendCommands", opts, 2, a0, a1, r0)
	return
}

func (p raftImpl) LocalRead(a0 *context.Context, a1 *LocalReadReq, opts ...client.CallOption) (r0 *LocalReadRsp, r1 error) {
	r0 = new(LocalReadRsp)
	r1 = p.Request2("raft.LocalRead", opts, 2, a0, a1, r0)
	return
}

func (p raftImpl) LinnerRead(a0 *context.Context, a1 *LinnerReadReq, opts ...client.CallOption) (r0 *LinnerReadRsp, r1 error) {
	r0 = new(LinnerReadRsp)
	r1 = p.Request2("raft.LinnerRead", opts, 2, a0, a1, r0)
	return
}

func (p raftImpl) AddServer(a0 *context.Context, a1 *AddServerReq, opts ...client.CallOption) (r0 *AddServerRsp, r1 error) {
	r0 = new(AddServerRsp)
	r1 = p.Request2("raft.AddServer", opts, 2, a0, a1, r0)
	return
}

func (p raftImpl) RemoveServer(a0 *context.Context, a1 *RemoveServerReq, opts ...client.CallOption) (r0 *RemoveServerRsp, r1 error) {
	r0 = new(RemoveServerRsp)
	r1 = p.Request2("raft.RemoveServer", opts, 2, a0, a1, r0)
	return
}
