// Code generated by protoc-gen-go-lrpc. DO NOT EDIT.
package raft

/*
   @Generator   : protoc-gen-go-lrpc
   @CreateTime  : 2026-09-11 19:07:39.36178 +0800 CST
   @Author      : NoAuthor
   @Comment     : code is auto generate do not edit
*/

import (
	"github.com/nyan233/littlerpc/core/client"
	"github.com/nyan233/littlerpc/core/common/context"
)

var (
	_ callera2c4bfe0da18477ab57295ac6b3eb187 = new(client.Client)
	_ RaftProxy                              = new(raftImpl)
)

type callera2c4bfe0da18477ab57295ac6b3eb187 interface {
	Request2(service string, opts []client.CallOption, reqCount int, args ...interface{}) error
}

type RaftProxy interface {
	RequestVote(a0 *context.Context, a1 *RequestVoteReq, opts ...client.CallOption) (r0 *RequestVoteRsp, r1 error)
	AppendEntries(a0 *context.Context, a1 *AppendEntriesReq, opts ...client.CallOption) (r0 *AppendEntriesRsp, r1 error)
	InstallSnapshot(a0 *context.Context, a1 *InstallSnapshotReq, opts ...client.CallOption) (r0 *InstallSnapshotRsp, r1 error)
}

type raftImpl struct {
	callera2c4bfe0da18477ab57295ac6b3eb187
}

func NewRaft(b callera2c4bfe0da18477ab57295ac6b3eb187) RaftProxy {
	proxy := new(raftImpl)
	c, ok := b.(callera2c4bfe0da18477ab57295ac6b3eb187)
	if !ok {
		panic("the argument is not implemented caller")
	}
	proxy.callera2c4bfe0da18477ab57295ac6b3eb187 = c
	return proxy
}

func (p raftImpl) RequestVote(a0 *context.Context, a1 *RequestVoteReq, opts ...client.CallOption) (r0 *RequestVoteRsp, r1 error) {
	r0 = new(RequestVoteRsp)
	r1 = p.Request2("raft.RequestVote", opts, 2, a0, a1, r0)
	return
}

func (p raftImpl) AppendEntries(a0 *context.Context, a1 *AppendEntriesReq, opts ...client.CallOption) (r0 *AppendEntriesRsp, r1 error) {
	r0 = new(AppendEntriesRsp)
	r1 = p.Request2("raft.AppendEntries", opts, 2, a0, a1, r0)
	return
}

func (p raftImpl) InstallSnapshot(a0 *context.Context, a1 *InstallSnapshotReq, opts ...client.CallOption) (r0 *InstallSnapshotRsp, r1 error) {
	r0 = new(InstallSnapshotRsp)
	r1 = p.Request2("raft.InstallSnapshot", opts, 2, a0, a1, r0)
	return
}
