syntax = "proto3";

package raft;
option go_package = "message/raft";

service raft {
  rpc RequestVote(RequestVoteReq) returns (RequestVoteRsp);
  rpc AppendEntries(AppendEntriesReq) returns (AppendEntriesRsp);
  rpc InstallSnapshot(InstallSnapshotReq) returns (InstallSnapshotRsp);
  rpc GetLeader(GetLeaderReq) returns (GetLeaderRsp);
  rpc AppendCommands(AppendCommandsReq) returns (AppendCommandsRsp);
  rpc LocalRead(LocalReadReq) returns (LocalReadRsp);
  rpc LinnerRead(LinnerReadReq) returns (LinnerReadRsp);
  rpc AddServer(AddServerReq) returns (AddServerRsp);
  rpc RemoveServer(RemoveServerReq) returns (RemoveServerRsp);
}


enum State {
  StateNil = 0;
  StateLeader = 1;
  StateFollower = 2;
  StateCandidate = 3;
}

enum CommandType {
  NoOpCommand = 0;
  UserCommand = 1;
  MemberChangeCommand = 2;
}

enum ErrCode {
  ErrOk = 0;
  ErrNoLeader = 10010;
  ErrCurrentIsAddServer = 10011;
  ErrCurrentIsRemoveServer = 10012;
  ErrChangeServerExists = 10013;
  ErrChangeServerNotFound = 10014;
}

message RequestVoteReq {
  uint64 term = 1;
  string candi_date_id = 2;
  uint64 last_log_index = 3;
  uint64 last_log_term = 4;
}

message RequestVoteRsp {
  uint64 term = 1;
  bool vote_granted = 2;
}

message AppendEntriesReq {
  uint64 term = 1;
  string leader_id = 2;
  uint64 prev_log_index = 3;
  uint64 prev_log_term = 4;
  repeated Entry entries = 5;
  uint64 leader_commit = 6;
}

message AppendEntriesRsp {
  uint64 term = 1;
}

message Entry {
  uint64 term = 1;
  uint64 log_index = 2;
  uint32 command_type = 3;
  bytes command = 4;
}

message InstallSnapshotReq {
  uint64 term = 1;
  string leaderId = 2;
  uint64 lastIncludedIndex = 3;
  uint64 lastIncludedTerm = 4;
  uint64 offset = 5;
  bytes data = 6;
  bool done = 7;
}

message InstallSnapshotRsp {
  uint64 term = 1;
}

message GetLeaderReq {

}

message GetLeaderRsp {
  string leader_id = 1;
  string leader_ip = 2;
}

message AppendCommandsReq {
  repeated bytes commands = 1;
}

message AppendCommandsRsp {
  uint64 last_log_index = 1;
  uint64 last_log_term = 2;
}

message LocalReadReq {
  string serial_no = 1;
  bytes command = 2;
}

message LocalReadRsp {
  bytes data = 1;
}

message LinnerReadReq {
  string serial_no = 1;
  bytes command = 2;
}

message LinnerReadRsp {
  bytes data = 1;
}

message AddServerReq {
  string new_server = 1;
}

message AddServerRsp {
  string leader_hint = 1;
}

message RemoveServerReq {
  string old_server = 1;
}

message RemoveServerRsp {
  string leader_hint = 2;
}

message LogMemberChange {
  repeated string old = 1;
  repeated string new = 2;
}